
[mcp_servers.herd]
command = "php"
args = ["C:/Users/amari/.config/herd/bin/herd-mcp.phar"]
cwd = "C:\\laragon\\www\\new-mundo-futuro-2026"

[mcp_servers.herd.env]
SITE_PATH = "C:\\laragon\\www\\new-mundo-futuro-2026"

[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
cwd = "/Users/acenaga/Herd/new-mundo-futuro"
